# Generated by Django 3.2.15 on 2022-10-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0002_metricgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prom.metricgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='rules_hint',
            field=models.TextField(default='xxxx'),
            preserve_default=False,
        ),
    ]
