# Generated by Django 3.2.15 on 2022-10-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0003_auto_20221014_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='prom.metricgroup'),
        ),
    ]
