# Generated by Django 3.2.15 on 2022-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='notification_address',
            field=models.TextField(default='mingmingtang@aliyun.com'),
            preserve_default=False,
        ),
    ]
