# Generated by Django 3.2.15 on 2022-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0002_subscribe_notification_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default='aaaa', max_length=50),
            preserve_default=False,
        ),
    ]
